export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT'
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const LOADING_STATE = 'LOADING_STATE';

//ASYNC
export const LOAD_PRODUCTS_SUCCEEDED = 'LOAD_PRODUCTS_SUCCEEDED'
export const LOAD_PRODUCTS_FAILED = 'LOAD_PRODUCTS_FAILED'
export const LOAD_PRODUCTS_REQUESTED = 'LOAD_PRODUCTS_REQUESTED'